### ISSUE TITLE
MDI avoid scrollbars when new window fits inside area

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#38] opened 2023-03-01 20:35 UTC
**Describe the bug**
On Windows when opening object properties (MDI Subwindows) they open too high in Y.
The subwindow frame is invisible (above MDI area's top) so it cannot be closed or moved.

**Comment by gfgit** [comment] 2023-03-01 20:41
Sorry I just noticed the scrollbar.
Not so intuitive when there is enough space in the Mainwindow to show new window without adding scrollbars.

**Comment by reinder** [comment] 2023-03-02 22:35
If you are connected to a world you've been connected to in the past it will try to restore the window position (based on the object id). Does it also happen when you create a new world and then open something for the first time?

**Comment by reinder** [comment] 2023-05-07 20:28
@gfgit do you still have this issue, or was it caused by saved dialog locations?

**Comment by gfgit** [comment] 2023-05-08 01:12
> @gfgit do you still have this issue, or was it caused by saved dialog locations?

I think it was saved locations

**Comment by gfgit** [comment] 2023-05-08 01:14
Although Linux and Windows behave differently in new world.
Windows stacks subwindows on top of each other while Linux VM tiles subwindows in rows which is very elegant.
It might be Qt mimic'ing platform native behaviour

**Comment by reinder** [comment] 2023-05-08 10:18
For the Traintastic UX it would be best if it behaves the same on all platforms, but that is more a low prio feature. Closing this one.

**Closed** 2023-05-08 10:18 UTC
Labels: bug
