### ISSUE TITLE
Server crash on Client disconnect

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#47] opened 2023-04-03 21:18 UTC
**Describe the bug**
Server crash while being debugged (also client was being debugged)

**To Reproduce**
1. Debug both server and client
2. Mess around with trains and rail vehicles
3. Kill client

<details>
<summary>GDB Backtrace</summary>

```
Thread 17 (Thread 25100.0x550c):
#0  0x00007ffc862f0b14 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00007ffc862a2e17 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 16 (Thread 25100.0x5f60):
#0  0x00007ffc862f0b14 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00007ffc862a2e17 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 12 (Thread 25100.0x5c90 "z21"):
#0  0x00007ffc862ed1e4 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00007ffc83ddf35f in ?? () from C:\WINDOWS\System32\KernelBase.dll
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 11 (Thread 25100.0x157c):
#0  0x00007ffc862ed144 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00007ffc83da306e in ?? () from C:\WINDOWS\System32\KernelBase.dll
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 7 (Thread 25100.0x563c "server"):
#0  0x00007ffc862ed464 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00007ffc83db0a2e in ?? () from C:\WINDOWS\System32\KernelBase.dll
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 6 (Thread 25100.0x4ba4):
#0  0x00007ffc862ed144 in ?? () from C:\WINDOWS\SYSTEM32\ntdll.dll
No symbol table info available.
#1  0x00007ffc83da306e in ?? () from C:\WINDOWS\System32\KernelBase.dll
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 1 (Thread 25100.0x5e9c):
#0  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_get_use_count (this=0xfeeefeeefeeefeee) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/shared_ptr_base.h:230
No locals.
#1  0x00007ff75320a3d8 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_lock_nothrow (this=0xfeeefeeefeeefeee) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/shared_ptr_base.h:272
        __count = 444
#2  0x00007ff7531d0d89 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count (this=0x4a1edfee68, __r=...) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/shared_ptr_base.h:1244
No locals.
#3  0x00007ff7531be128 in std::__shared_ptr<Client, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<Client, void> (this=0x4a1edfee60, __r=...) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/shared_ptr_base.h:1548
No locals.
#4  0x00007ff7531857d0 in std::shared_ptr<Client>::shared_ptr<Client, void> (this=0x4a1edfee60, __r=...) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/shared_ptr.h:381
No locals.
#5  0x00007ff75323db60 in std::enable_shared_from_this<Client>::shared_from_this (this=0x1bc785c2e28) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/shared_ptr.h:935
No locals.
#6  0x00007ff752f28f13 in operator() (__closure=0x4a1edff040) at C:/Filippo/Qt_Project/traintastic/server/src/network/client.cpp:247
        this = 0x1bc785c2e20
#7  0x00007ff752f2dc26 in std::__invoke_impl<void, Client::disconnect()::<lambda()>::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/invoke.h:61
No locals.
#8  0x00007ff752f2d592 in std::__invoke<Client::disconnect()::<lambda()>::<lambda()>&>(struct {...} &) (__fn=...) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/bits/invoke.h:96
No locals.
#9  0x00007ff752f2c8a8 in std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()>::__call<void>(std::tuple<> &&, std::_Index_tuple<>) (this=0x4a1edff040, __args=...) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/functional:484
No locals.
#10 0x00007ff752f2c4d1 in std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()>::operator()<>(void) (this=0x4a1edff040) at C:/Filippo/bin/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/c++/functional:567
No locals.
#11 0x00007ff752f2bf11 in boost::asio::asio_handler_invoke<std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> >(std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> &, ...) (function=...) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/handler_invoke_hook.hpp:69
No locals.
#12 0x00007ff752f2bd18 in boost_asio_handler_invoke_helpers::invoke<std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()>, std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> >(std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> &, std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> &) (function=..., context=...) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/detail/handler_invoke_helpers.hpp:37
No locals.
#13 0x00007ff752f2bafa in boost::asio::detail::handler_work<std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()>, boost::asio::system_executor, boost::asio::system_executor>::complete<std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> >(std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> &, std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> &) (this=0x4a1edff05f, function=..., handler=...) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/detail/handler_work.hpp:100
No locals.
#14 0x00007ff752f2b6df in boost::asio::detail::completion_handler<std::_Bind<Client::disconnect()::<lambda()>::<lambda()>()> >::do_complete(void *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (owner=0x1bc786c3fd0, base=0x1bc7858b8d0) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/detail/completion_handler.hpp:70
        b = {<boost::asio::detail::noncopyable> = {<No data fields>}, <No data fields>}
        h = 0x1bc7858b8d0
        p = {h = 0x4a1edff040, v = 0x0, p = 0x0}
        w = {<No data fields>}
        handler = {<std::_Weak_result_type<Client::disconnect()::<lambda()>::<lambda()> >> = {<std::_Weak_result_type_memfun<Client::disconnect()::<lambda()>::<lambda()>, false>> = {<std::_Weak_result_type_impl<Client::disconnect()::<lambda()>::<lambda()> >> = {<std::_Maybe_get_result_type<Client::disconnect()::<lambda()>::<lambda()>, void>> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, _M_f = {__this = 0x1bc785c2e20}, _M_bound_args = {<No data fields>}}
#15 0x00007ff753023edc in boost::asio::detail::win_iocp_operation::complete (this=0x1bc7858b8d0, owner=0x1bc786c3fd0, ec=..., bytes_transferred=0) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/detail/win_iocp_operation.hpp:47
No locals.
#16 0x00007ff753025937 in boost::asio::detail::win_iocp_io_context::do_one (this=0x1bc786c3fd0, msec=4294967295, ec=...) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/detail/impl/win_iocp_io_context.ipp:459
        on_exit = {io_context_ = 0x1bc786c3fd0}
        op = 0x1bc7858b8d0
        result_ec = {val_ = 0, failed_ = false, cat_ = 0x7ff7535244f0 <boost::system::detail::cat_holder<void>::system_category_instance>}
        completion_key = 0
        overlapped = 0x1bc7858b8d0
        ok = 1
        bytes_transferred = 0
        last_error = 0
#17 0x00007ff753025531 in boost::asio::detail::win_iocp_io_context::run (this=0x1bc786c3fd0, ec=...) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/detail/impl/win_iocp_io_context.ipp:202
        this_thread = {<boost::asio::detail::thread_info_base> = {<boost::asio::detail::noncopyable> = {<No data fields>}, reusable_memory_ = {0x1bc78583040, 0x0, 0x0}}, <No data fields>}
        ctx = {<boost::asio::detail::noncopyable> = {<No data fields>}, key_ = 0x1bc786c3fd0, value_ = 0x4a1edff280, next_ = 0x0}
        n = 303
#18 0x00007ff7530038c6 in boost::asio::io_context::run (this=0x7ff75334d9b0 <EventLoop::ioContext>) at C:/Filippo/Qt_Project/traintastic/server/thirdparty/boost/boost/asio/impl/io_context.ipp:63
        ec = {val_ = 0, failed_ = false, cat_ = 0x7ff7535244f0 <boost::system::detail::cat_holder<void>::system_category_instance>}
        s = 140700227994924
#19 0x00007ff7530ad72d in EventLoop::exec () at C:/Filippo/Qt_Project/traintastic/server/src/core/eventloop.hpp:52
        work = {<std::__shared_ptr<boost::asio::io_context::work, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<boost::asio::io_context::work, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x1bc785567c0, _M_refcount = {_M_pi = 0x1bc785567b0}}, <No data fields>}
#20 0x00007ff752f52c13 in Traintastic::run (this=0x1bc786c4d60, worldUUID=..., simulate=false, online=false, power=false, run=false) at C:/Filippo/Qt_Project/traintastic/server/src/traintastic/traintastic.cpp:218
        boostVersion = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7ff75371f470 <Traintastic::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool, bool)::boostVersion+16> "boost 1.71.0"}, _M_string_length = 12, {_M_local_buf = "boost 1.71.0\000\000\000", _M_allocated_capacity = 3328477284128485218}}
#21 0x00007ff752dc1bf3 in main (argc=1, argv=0x1bc786c1b20) at C:/Filippo/Qt_Project/traintastic/server/src/main.cpp:123
        options = {tray = false, dataDir = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x4a1edff608 ""}, _M_string_length = 0, {_M_local_buf = "\000\006\000\000\000\000\000\000\000�������", _M_allocated_capacity = 1536}}, world = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<std::__new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x4a1edff628 ""}, _M_string_length = 0, {_M_local_buf = "\000m4��\177\000\000\220Dlx�\001\000", _M_allocated_capacity = 140722560068864}}, simulate = false, online = false, power = false, run = false}
        dataDir = {static preferred_separator = 92 L'\\', _M_pathname = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<wchar_t>> = {<std::__new_allocator<wchar_t>> = {<No data fields>}, <No data fields>}, _M_p = 0x1bc78543ee0 L"C:\\Users\\Filippo\\AppData\\Local\\traintastic\\server"}, _M_string_length = 49, {_M_local_buf = L"1\000\000\000\000\000\000", _M_allocated_capacity = 49}}, _M_cmpts = {_M_impl = {_M_t = {<std::__uniq_ptr_impl<std::filesystem::__cxx11::path::_List::_Impl, std::filesystem::__cxx11::path::_List::_Impl_deleter>> = {_M_t = {<std::_Tuple_impl<0, std::filesystem::__cxx11::path::_List::_Impl*, std::filesystem::__cxx11::path::_List::_Impl_deleter>> = {<std::_Tuple_impl<1, std::filesystem::__cxx11::path::_List::_Impl_deleter>> = {<std::_Head_base<1, std::filesystem::__cxx11::path::_List::_Impl_deleter, true>> = {_M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, std::filesystem::__cxx11::path::_List::_Impl*, false>> = {_M_head_impl = 0x1bc786c44a0}, <No data fields>}, <No data fields>}}, <No data fields>}}}}
        enableConsoleLogger = true
        status = 0
        restart = false
```

</details>

**Expected behavior**
No crash

**World export**
[Train Throttle 2023-04-03.zip](https://github.com/traintastic/traintastic/files/11142564/Train.Throttle.2023-04-03.zip)

**Traintastic:**
 - OS: Windows 10 64-bit
 - Version: PR #44 

**Connected hardware**
None

**Comment by reinder** [comment] 2023-04-07 21:13
Does the server also crash when running it in Release?

**Comment by reinder** [comment] 2023-04-08 06:53
I just got it too, it does not happen always, so now find a way to reproduce it....

**Comment by reinder** [comment] 2023-05-13 21:49
I'd suspect this is related to #58 , the server is probably crashing due to signal still being connected to objects that are gone. I'd think is was caused by: 95169b4d8f2798d6fbd419efb4460ed9edec3408

**Comment by reinder** [comment] 2023-10-27 14:06
@gfgit do you still have this issue on recent builds?

**Comment by reinder** [comment] 2023-12-04 16:25
@gfgit do you still have this issue with current master?

**Comment by gfgit** [comment] 2023-12-07 18:08
EDIT: It does not seem to crash if I manually disconnect from client but I made it crash by closing client window while connected.
But maybe it's a different bug

**Comment by reinder** [comment] 2024-02-19 18:39
I close this one for now, I tried many times, but it didn't crash. (If it does we can reopen it or create a new one.)

**Closed by reinder** 2024-02-19 18:39 UTC
Labels: bug
